name: GabrielleLods
favicon: null
layout_spectrum: 0.5346151837147772
typography_spectrum: 0.05218023690395057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.44781971885822713
  lightness: 0.9369689687155187
  saturation: 0.3035183206666261
  rhythmicContrast: 0.34651144430972636
purpose: []
